pipeline {
    agent any

    stage(‘Set Terraform path’) {
        steps {
            script {
                def tfHome = tool name: ‘Terraform’
                env.PATH = “${tfHome}:${env.PATH}”
            }
            sh ‘terraform — version’
        }
    }

    stage(‘Provision infrastructure’) {
        steps {
            dir(‘infrastructure’) {
                sh ‘terraform init’
                sh ‘terraform plan -out=plan’
                // sh ‘terraform destroy -auto-approve’
                // sh ‘terraform apply --auto-approve’
            }
        }
    }
}
