pipeline {
    agent any

    environment {
        tfHome = tool name: 'terraform'
        PATH = "${tfHome}:${PATH}"
        TF_VAR_bucket_name = "${BUCKET_NAME}"
        TF_VAR_bucket_region = "${BUCKET_REGION}"
        TF_VAR_instance_region = "${REGION}"
    }

    stages {
        stage('Generate Key-Value Pair') {
            steps { sh 'ssh-keygen -f ./infrastructure/mykey' }
        }

        stage('Ensure Terraform Installation') {
            steps { sh 'terraform --version' }
        }

        stage('Provision infrastructure') {
            steps {
                dir('infrastructure') {
                    sh 'terraform init'
                    sh '''
                        terraform plan --out=plan \
                        -var 'access_key=${ACCESS_KEY}' \
                        -var 'secre_key=${SECRET_KEY}'
                    '''
                    // sh 'terraform destroy -auto-approve'
                    // sh 'terraform apply plan'
                }
            }
        }
    }
}